modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory
license="MIT License"

[[mods]] #mandatory
modId = "fishermens_trap" #mandatory
version = "${file.jarVersion}" #mandatory
authors = "Uraneptus" #optional
credits = "Assets and Idea by toomanykitkats" #optional
displayName = "Fishermens Trap" #mandatory
description = '''
A mod that adds a fish trap to passively collect fish by using vanilla items as baits.'''
displayTest = "MATCH_VERSION"

[[dependencies.fishermens_trap]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.fishermens_trap]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"